const MAX_PROFILE_PHOTO_SIZE = 5;

const ALERT_MESSAGE_PASSWORD_RESET_SUCCESS = "Password reset successful";
const ALERT_MESSAGE_SUCCESSFULLY_SENT_EMAIL_TO_RESET_PASSWORD =
  "Successfully sent email to reset password";
const ALERT_MESSAGE_INVALID_EMAIL = " Please provide a valid email";
const ALERT_MESSAGE_INVALID_CREDENTIAL = "Invalid email or password";
const ALERT_MESSAGE_EMAIL_ALREADY_USED = "Email already used";
const ALERT_MESSAGE_USER_PROFILE_SETUP_SUCCESS =
  "User information saved successfully";
const ALERT_MESSAGE_PAYMENT_INFORMATION_SAVE_SUCCESS =
  "Payment information saved successfully";
const ALERT_MESSAGE_PAYMENT_METHOD_EXISTS = "Payment method already exists";
const ALERT_MESSAGE_PAYMENT_UPDATE_SUCCESS =
  "Payment information updated successfully";
const ALERT_MESSAGE_PAYMENT_NOT_SETUP = "Payment information setup not found";
const ALERT_MESSAGE_AT_LEAST_ONE_PACKAGE_SUBSCRIPTION =
  "Please subscribe at least one package to create event";
const ALERT_MESSAGE_PERSONAL_INFORMATION_UPDATE_SUCCESS =
  "Personal information updated successfully";
const ALERT_MESSAGE_CAN_NOT_USE_PREVIOUS_PASSWORD =
  "You can not use previous password as your new password!";

module.exports = {
  MAX_PROFILE_PHOTO_SIZE,
  ALERT_MESSAGE_PASSWORD_RESET_SUCCESS,
  ALERT_MESSAGE_SUCCESSFULLY_SENT_EMAIL_TO_RESET_PASSWORD,
  ALERT_MESSAGE_INVALID_EMAIL,
  ALERT_MESSAGE_INVALID_CREDENTIAL,
  ALERT_MESSAGE_EMAIL_ALREADY_USED,
  ALERT_MESSAGE_USER_PROFILE_SETUP_SUCCESS,
  ALERT_MESSAGE_PAYMENT_INFORMATION_SAVE_SUCCESS,
  ALERT_MESSAGE_PAYMENT_METHOD_EXISTS,
  ALERT_MESSAGE_PAYMENT_UPDATE_SUCCESS,
  ALERT_MESSAGE_PAYMENT_NOT_SETUP,
  ALERT_MESSAGE_AT_LEAST_ONE_PACKAGE_SUBSCRIPTION,
  ALERT_MESSAGE_PERSONAL_INFORMATION_UPDATE_SUCCESS,
  ALERT_MESSAGE_CAN_NOT_USE_PREVIOUS_PASSWORD,
};
